---
apiVersion: v1
kind: Namespace
metadata:
  name: kiali-operator
  labels:
    name: kiali-operator
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kiali
  namespace: flux-system
spec:
  interval: 24h
  url: https://kiali.org/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kiali-operator
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: kiali-operator
      version: "2.17.0"
      sourceRef:
        kind: HelmRepository
        name: kiali
  targetNamespace: kiali-operator
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    cr:
      create: true
      namespace: istio-system
      spec:
        # Kiali configuration
        auth:
          strategy: anonymous  # For homelab, no auth needed
        deployment:
          accessible_namespaces:
          - "**"  # Access all namespaces
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 512Mi
        external_services:
          prometheus:
            url: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
          grafana:
            enabled: true
            in_cluster_url: http://monitoring-kube-prometheus-stack-grafana.monitoring.svc.cluster.local
            url: https://grafana.dunde.live
        server:
          port: 20001
          web_root: ""
