---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: flux-system
spec:
  interval: 15m
  timeout: 10m
  chart:
    spec:
      chart: reflector
      version: ">=7.1.0"
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
  targetNamespace: reflector-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi