---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-ai
  namespace: flux-system
spec:
  interval: 20m
  timeout: 15m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/apps/base/ai
  prune: true
  wait: false
  serviceAccountName: gotk-n8n-reconciler
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: apps-monitoring
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: n8n
      namespace: flux-system