---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-media
  namespace: flux-system
spec:
  interval: 20m
  timeout: 20m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/apps/base/media
  prune: true
  wait: false 
  serviceAccountName: gotk-media-server-reconciler
  dependsOn:
    - name: infrastructure-security-policies  # Changed from enrollment to policies (ingress only)
