---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-monitoring-extras
  namespace: flux-system
spec:
  interval: 20m
  path: ./flux/apps/base/monitoring-extras
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: apps-monitoring
  healthChecks:
    - apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      name: flux-system
      namespace: monitoring