---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-backup-schedules
  namespace: flux-system
spec:
  interval: 20m0s
  path: ./flux/infrastructure/base/backup-schedules
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure-backup
  timeout: 20m
  wait: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: velero
      namespace: velero