---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-platform
  namespace: flux-system
spec:
  interval: 20m
  timeout: 20m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/infrastructure/base/networking
  prune: true
  wait: true
  dependsOn:
    - name: infrastructure-core