apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
    annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
type: Opaque
data:
    xtunnelName: ENC[AES256_GCM,data:nsGgk4s/Mgx2+tbMiMwNGA==,iv:xmOtsj4chLGkn3CTagg3lGV6sUNihgJQEoJIgmOwON4=,tag:ycik57WfRa5SdAw4noJU/g==,type:str]
    xaccountId: ENC[AES256_GCM,data:lY6tVYTo94y1pdd/vvCJuq0xHGby949NUSWXV4N2pr0WXEeiDvYUhsPZggk=,iv:GYU0x2mRoco736TRE3JZL8B8lisSdUjDnwjtgIcv0c0=,tag:aCobvEbJmL4ICbbiczKiRA==,type:str]
    cloudflare-token: ENC[AES256_GCM,data:UPvhV3kg2PIwuo6FsTs0Z5XyCbhKTSNuDg28Uc2lwz6fegbB9trMGv+tIPj1QRxV85WbNYIR4R8=,iv:GrO04HshZ55zI7kYdeypArmW7M+sZill65I6uLi9r0Q=,tag:qVIpAdvTSLvvraXJlMpX9A==,type:str]
sops:
    age:
        - recipient: age1gs033enz7qcwvpy9jq7c5mw4w4p0sshuqkm84dzc3jkg9zyt6gdqauejv2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4djhKZ0ZTdDFST0ZEazRG
            a3l4M0hwU2ptRi9jalN6K0lScUZ4UE41ejFBCllnL0M1R0EvY01MSHByWFQxRi9J
            VldqQlBxdHVuU2RpNnNlV0VuclRFdTgKLS0tIFJJT2M2WFJicU1aTkxMSGplZGdW
            U1JZM1hHV1NDYW9lWm51Tm1Ra3gyUHMKFcu4kRXIAHoJHFskGQL3ZCnx7SkCe1rd
            zyak3s8U/3wuzOwR8kdOcD03SS80bjI8WLE2ZBDZRL6+weDRtJNPyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-03T14:34:54Z"
    mac: ENC[AES256_GCM,data:BtxB03qlch4sCgwVsk5suqLrsLJrxI7HzWkHCafT6vuunBKnacI+gIwTb5+g36o+UbYL1YLd/8qoFqQAShTLkfsew8ce25On5RffL7zOspxC4evUFBawjIRCQnYLKyBLS/TCdMjfPk8/AxC7632xKUICjr3HtKhg1chEUgL5Avo=,iv:q4PGM1XlprsL1LPbK+jQtPgnxCtQ1wNHWkJjILtVLeM=,tag:HSEg6AFNU4lJPINMZKVckA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
