---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-rbac.yaml
  - cloudflare-secret.yaml
  - cert-issuers.yaml
  - istio-gateway.yaml
  - istio-external-services.yaml
  - kiali.yaml
  - trivy-operator.yaml
  - telegram-secret.yaml
  - telegram-provider.yaml
  - telegram-alert.yaml
  - dunde-live-certificate.yaml