apiVersion: v1
kind: Secret
metadata:
    name: hoarder-secrets
    namespace: hoarder
type: Opaque
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:uUSRITatD0zvGiEx9wH7zjJGAaqO0JdkHR5IPteTj0xDmvYzQwArZ/Hp+tbFXb4W,iv:TamTLs4a4QNCcukI2FsGZQH4pdyrLK4ToG3HX7+Xkok=,tag:7AdDO1FAo13S/PWX5jamKg==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:q7QYYsCMZYXlbKm87U8aiH83RVfVu/baFRB/EWCDw8OFw1HJ91nJaFuJ2Uh1q/NI,iv:Ix8HBIiexXgB3Lg5EmSAHaEeod+cSXVmvTgiYj49eLw=,tag:YM+JHspIeZl1pAAaGRU8fw==,type:str]
sops:
    age:
        - recipient: age1gs033enz7qcwvpy9jq7c5mw4w4p0sshuqkm84dzc3jkg9zyt6gdqauejv2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2enpKU0RaU1cwQlo0QkJm
            U291ajBsTzI2T0sxY3I4aUNyU2JmVEYzckhZClNPZEIra0FWaVR4S3c0N0crejVu
            MVlyUWdYZ0QrV2g3S28rLzBKaFg5M3cKLS0tIDF5czNxU1B1YTNaTWYvMCtFZWxV
            UUU2OXI3VzVtcVpnM2drVWF3RDZYRVEK08wmYiTlWIQTMgO1zIGH7iYO9qU2B4wO
            8DvGAFKwOXvOZrSCcmzk0VAuNW1Z/iv+OxEXIhy1vo06qckwMbdwxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-03T14:44:39Z"
    mac: ENC[AES256_GCM,data:Xz1Q82siMoNWYarZzKr5l5C+u3whFCSmmoo79P+Av3ha7I/p9EdjvmyMc/WDTdN3qsv0VVuxsuisI+8dJJOd24IW2fHsWSL+qg8E+b01TRQxgpGyKhOytFcx3bGOTwiRdBYsgWlV7cfSBj3WB62KPy0fEdSi0c2b9AwMXTtKb5A=,iv:zVzA3I4KjTa2imBC67OpnID3a8tClrpP1YLw1vZm8SA=,tag:y5yWkyiD1bAlvvDQXEvb/A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
