---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: n8n
  namespace: flux-system
spec:
  interval: 12h
  url: oci://8gears.container-registry.com/library/n8n
  ref:
    tag: "1.0.15@sha256:7872c404bbf013704e5e616fd43e3fc5d78436694d4e7f58e9dc5c78347ad725"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: flux-system
spec:
  interval: 15m
  timeout: 20m
  chartRef:
    kind: OCIRepository
    name: n8n
    namespace: flux-system
  targetNamespace: n8n
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: n8n-values
      valuesKey: values.yaml