---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: n8n
  namespace: flux-system
spec:
  interval: 12h
  url: oci://8gears.container-registry.com/library/n8n
  ref:
    tag: "1.1.0@sha256:8fdc002d7482973bef7edda2fd3044e5d02bfa746457457e20462a896933e5d3"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n
  namespace: flux-system
spec:
  interval: 15m
  timeout: 20m
  chartRef:
    kind: OCIRepository
    name: n8n
    namespace: flux-system
  targetNamespace: n8n
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: n8n-values
      valuesKey: values.yaml