apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-app
    namespace: n8n
type: Opaque
data:
    username: ENC[AES256_GCM,data:zF+eQA==,iv:2pecz8dH/UrZmNkpnfbdHEoiikHWelaA8aWsDjqDe60=,tag:qVzkv3qa9Y6zRMTjVf1juw==,type:str]
    password: ENC[AES256_GCM,data:mla2FBKaaE92jHg8gCDc846xGhESMDHxhakEVQFVzM/+9XFORI/F5vRWe6jQw/u3QnXT2NqDpDY=,iv:dTM0etEiW5qjHXe8EG9eK9CBau+JlLttvGRkToPJXMY=,tag:ZsR3+6EpffiHARAt6rswiA==,type:str]
sops:
    age:
        - recipient: age1gs033enz7qcwvpy9jq7c5mw4w4p0sshuqkm84dzc3jkg9zyt6gdqauejv2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYkl3eUU0TWVFWDBXUmpy
            L3VzQWlzSk11T2pTc09yR1RxMUQxN0cvMmtZCmxGSjljUnFGWXVxWmtlclJGWFpG
            S1JQVk5BRzdyWm4rUjVwK21YSlR0cGsKLS0tIEJydUtRRXlFblpLUlZocDRRQlI3
            YlZVY3RFVHN5OFF5Z014RjFmMEIxbVEKNbcWWSMXlQFbVPZPayKde/9Yjxw/ce8q
            4p9L6Kw7VYymSVwzb9LiBbY4+eJCVOXG6qVyaIvHLUjJZ2wXFOXo9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-07T10:50:40Z"
    mac: ENC[AES256_GCM,data:ZLhu7RuelPWS8XZ7Wy4w9Gesmn+PrhBrslCqXTbQ81x9fHWXK47BvstijzP/GmDf5uChmfmEbmVVaVG+jWs5pZbx2KK1yomd+y0JJAzbZExcs+q1jKoUZDKU33F8tJfmmrYzje8NFiUl2JNCmf59axCGuLMxb2kboJ5tK2y7O/E=,iv:Qz1vy1R23J/zeWYIlHQP1aclwRJGu82eRx9Gfg1pQE8=,tag:IlzWbfzOeoYwKVStbG020w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
