---
apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-values
  namespace: flux-system
data:
  values.yaml: |
    # Minimal n8n configuration - disable problematic components
    n8n:
      image:
        repository: n8nio/n8n
        tag: 1.81.0 # {"$imagepolicy": "flux-system:n8n:tag"}
      
      config:
        database:
          type: postgresdb
          postgresdb:
            host: n8n-db-rw
            port: 5432
            database: app
            user: app
        
        executions:
          mode: regular
          
        generic:
          timezone: "UTC"
          
      secret:
        database:
          password:
            name: n8n-db-app
            key: password
        n8n:
          encryptionKey:
            name: n8n-encryption-key
            key: encryption-key
      
      persistence:
        enabled: true
        size: 10Gi
        
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 1000m
          memory: 2Gi
          
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
    
    # Disable problematic worker and webhook components
    worker:
      enabled: false
      
    webhook:
      enabled: false
    
    redis:
      enabled: false
      
    valkey:
      enabled: true