apiVersion: v1
kind: Secret
metadata:
    name: vexxy-pull-secret
    namespace: vexxy
    labels:
        app: vexxy
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:C/flCHZ1GxzmP7r7OdPo3RXOtbqDB51SwQ5xIN5C9Ro2iDuX/0a9cwyolUInc2A9tLFPV/3ZAvbETgbAWbP5fQVxULN0SY9XgU0OtglcKl0rS4c0zZW+U3BdPV18zKbvumwy1QCPvXnf,iv:kHSF4Bd+UNeofcTyyNez7vGWC2FkKywUIEhCJYzxXRQ=,tag:SazOqymX92i9JgEZcw1kXw==,type:str]
sops:
    age:
        - recipient: age1gs033enz7qcwvpy9jq7c5mw4w4p0sshuqkm84dzc3jkg9zyt6gdqauejv2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTlR3MVV6M1NJYWdXaUZ4
            Nm1aNnBvQ25SVWFwQ3B6RHFiZ3dtbER0bWtBCjhPQ2grbjRhSWdRb3hyaXIyWTlO
            THVpNWc3NTBmQU54bXlTcDBjSjZyYWcKLS0tIFc1bVhWa2V2bWlwMnRaME10K0Fa
            K2V0aDlnRFlOSklydkJuWERjMXIvSDQKs6z+1P5VI0LMnD2Y+RfIbpzqLjy/M18D
            CPY/UM5HyOVa5FtTwYT2QWnZaVzuxBZ590iJ3xsO6lvQwatHTuEbwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T08:46:55Z"
    mac: ENC[AES256_GCM,data:BoWaPS4uhiqvJ9p1yJgDa0+0K86so96q6FxnkItEg3clFBi5CZ7RCt01NelmAU7RvCYi2RdQonrk6ctBQcRILkH6hLozzux98tJOeF44RALsuG89bk4N2jezaLeyQdyifb6k9uvJCqct4o2UL/zRHmx15uoxzHYf37y6qw8iBSo=,iv:7cGP3d5MjfMgsjJtNRYJtOv/VrvwYI4ZzQVOgVUeZgU=,tag:hdlrg0JGUJu8nkI6sUvVTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
