apiVersion: v1
kind: Secret
metadata:
    name: vexxy-pull-secret
    namespace: vexxy
    labels:
        app: vexxy
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:Ju4VDBvbxEOP+sV2m0IhPpy3fyOKq0xWBCghOCXLGNX14YUXLahUzL0gFiwxzKOPe6cY75l/iq73Oc2hOyPUe3wLcz77SE49sTxjujTvUE6CpO2DmY1plf/tQpt9ep74wpnql9JAq9vO9gDw479zRbAzLQ7isMrwV5WWOOoctkRJa+xUguhaRp42tu3jlJP5q8LGA7a9D7rPOhsX,iv:7lHM5+64RxKVDH56ArQgTHT5iX3n22aoTX90kuiZnp0=,tag:kvDFkFr6uMkG1DpZhk1E2A==,type:str]
sops:
    age:
        - recipient: age1gs033enz7qcwvpy9jq7c5mw4w4p0sshuqkm84dzc3jkg9zyt6gdqauejv2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWGhISDc0UVpwWkdhY05Q
            Yk5IRmU1ckNic3lUd1F1OHYyUVo4VVRLM3pFCjdoc0lROGRJZGE2Vy9XQnlOem5U
            UHZCN1I1bEFIQ3dJSlQ5OGdEQmRBck0KLS0tIEpaamFzV29nTFpFSGI1Z3lVSm82
            NFZ2bU1wbWhOcXdIRkttZjhxcy9JTnMKJ0GdB0i5+2vkfgbgg7dUiZKAl3o7jtwf
            DxPMhgaLcEgD9JofYfD/SWJcNebB4zQtNZhwgXA2X8SaUMJmGprDqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T00:22:58Z"
    mac: ENC[AES256_GCM,data:Amg0gTMhAmgu/qv8/bQ5I6WkruU8+utCtEMaSAFr5BsSxTXF0UZrfUhsmQsfDc/FmWM4zgtVbhfXTektnynbWh1SAIXRXeFumMGK3l0Mrqj5gKdvzv4jRpWsyAeG+TAdyF+E2v4Dq8HWV/gbU5qUJuu+Vge2rgh2tHrZJUTMXeo=,iv:P/t7+WNUuBA5xjf12/uw+kNGWP1SzMZJ0BFSPsScSjs=,tag:koXFti9LgZddutAANmo73Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
