apiVersion: v1
kind: Secret
metadata:
    name: vexxy-git-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:O/w/D8MrTyPP4jrYVQ==,iv:2SkeFIQ3IhPUEuno3Nb65dM+kQ5HdxnfMpZZaOgfqfE=,tag:vt+6ODuW+ATpElP2bIKihg==,type:str]
    password: ENC[AES256_GCM,data:qH8nerd4rRfwPhjW1sUsHwf5QIYQOg/Es6nZOKbj7exe1tkkWn/nTg==,iv:jtaX20nmF234zNzQHr0l5dwJ63MQtpF/McjEA0XJBUI=,tag:WJDHXSL6gDtF5XP7hgyqAQ==,type:str]
sops:
    age:
        - recipient: age1gs033enz7qcwvpy9jq7c5mw4w4p0sshuqkm84dzc3jkg9zyt6gdqauejv2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTEpsR3RIZmZaNUJmY3ZT
            SWFNRXZQMFo3a01SZUhyWHNOVmJ0cm1WTFJVClJiMlpyZWM1QTZOZEVkejZoR2l2
            cWdtTTRvcXVKNjFGYVNybUlEM0FCL0kKLS0tIEZTVEYyNGl1KzhFTmYvdTdBU3Rz
            MHFkZTV6OTE4SEdzYXh0NHRrNytyTzAKJcBuNOECOly3525nc6t7I1Jdt3f3RfAk
            gNj2yjaInwrHOaYoHOiIVASZTzlrxwz+8iGsI5tbHaZalnG6qOC0Ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T08:47:05Z"
    mac: ENC[AES256_GCM,data:6jDnpK7/Pxh6VMkPm/ryXhhzElq4DDXCo+nOOcy3hWx/LQ3lpDFgxN6B/JKUB0LIJ63tLLD6wVleAYG46aY/rYZjESqU0iZVS88JzpgP8PbjAIFrEEqQk6rBE0CZPEpCNk/nmRUoqAbxBCWjczXEGBKm1zTuuRBkljJ9OjfH0Bw=,iv:SKLAl9bEnuPoZt/tSP7B6cEPTWbdJ0PLESOEMFvEaO0=,tag:GxfO+HUnfgrcQIUD17c84A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
