apiVersion: v1
kind: Secret
metadata:
    name: vexxy-git-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Y74Nk1wGy9SGZghnHA==,iv:PbuMad6B4/T/3lZKO9s/gw1VmI7dP2yyRMki0lWhEQ4=,tag:brvNpjA2J5bgEkoHyvNmMA==,type:str]
    password: ENC[AES256_GCM,data:/aGMgsfNP5iYn75oEjypIzC/9G0FqCmqi9e72hSUmdIjcztwkW+jww==,iv:XdaqG6jSUctVXdMGEVBbxBRVAJhggbD0J8n9lRbJGQo=,tag:ZrNKE7vipUKqBuIJT4bNBw==,type:str]
sops:
    age:
        - recipient: age1gs033enz7qcwvpy9jq7c5mw4w4p0sshuqkm84dzc3jkg9zyt6gdqauejv2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQlMrUTMyV1QvR2tQbWpO
            YTc5YjZ1VmZpYzVZWUpuN2d5ZkNJdDZ0NTNNCmp2SlBlUUZPc2JRK0RGTy9zYlN4
            eHRkR2trd1ovZDNSOTRaSTBHeDBTUlUKLS0tIHhwVHBGT3J5d1ZVL1NqWlNxYVY0
            Qi9KWVEvUFNhSys5N2U5bkdIbGxqVGcKcsQV1UN9EXI7l3cZQFqOTpmIFbr51Zc5
            zVlBrcsaoXLvIco1naYqZe10bYzysfnV5Dhrs/Ppt1klFZSQhz0nKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T00:41:39Z"
    mac: ENC[AES256_GCM,data:PT71agdmsmktAZcsWr2IlmvMgAPD2JHasHPn25bHXdDl+nINukPAsr9xecDFZj7UbQyJvxI/D7inQTeW8t1ofYLu2uPpZ+wYPf+3mlgNuOZ+sj/QvO7itnViKGnQbXuvmQv7an22LjNTOSCbHNLyxvwbx1bRNPyRIHFNIAWKFBI=,iv:0TgGZuMbtqFaVkIRLexQ68jkfbjYwdTe8+rB6hgX8Mg=,tag:fvmvktFrWV52rqPrrrPBvw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
