apiVersion: v1
kind: Secret
metadata:
    name: vexxy-git-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:b3hvFkACYFMqEXXPMA==,iv:/vizxclh8TPjR+urtAEVeP+xux6DSBZo/3EjCXBmNsQ=,tag:QWic+XK7HUck51swgWOPJw==,type:str]
    password: ENC[AES256_GCM,data:1QuuQIQgwluAtKt0GwaYEnDiBUU6lZYgm7LXXOj6GLCU314JXTRiiw==,iv:plR+IDpUQCsLtMLaxU4t+XY1q+9A1vm2+WrnGeEXeds=,tag:26Y8Y9+ol10R1E4MiODy+A==,type:str]
sops:
    age:
        - recipient: age1gs033enz7qcwvpy9jq7c5mw4w4p0sshuqkm84dzc3jkg9zyt6gdqauejv2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNzN0K1BOQ01aUEZadDhi
            bCsxTDNWZHR0RlpiMHFxeFlCS09US1BqWTNnCkNSNjBWd3RVY2NGUlBJa01PK0F4
            ci90cGQ2ZzJwLzVxM2FteDBmS3Z6Y0EKLS0tIHYxVDB2TklPTi91bG02Q1E0Vmd2
            cUNPQm1FL3R2WnNxZGpibklKU3ZoWWcK1YTLBoPQBVEScksmQPXodXjEqR1Oq92l
            zJocrK86PvlDrMebZAHnkqpkVL28OsykJTSnFErqGCRy/ksOdm1vpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T00:23:30Z"
    mac: ENC[AES256_GCM,data:coWHAx/JPh7yk1uN1BA6sgBpdASdm/vqtACLVrAMn4C6vjkEjtzYJO8mSOZgUV/SKjUMrSar2lqkFMqVECv0wKDK78xSeu0U2RD1lLHaUw+P0lw89M/09wk+Sb5m1LDGqjFgtfBhBk4D6HjCSBLYzJ65bHIBOcj3k9LMJ5AGjwM=,iv:1K3totrM7gESfs0Okvl4f9JeuOie2FVziVhM2EBe8L4=,tag:RsSD5RP7JTD6W1ivCoc6AA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
