---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: vexxy
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/plpetkov-tech/all-vexxy.git
  ref:
    tag: v0.1.2
  secretRef:
    name: vexxy-git-auth
