---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: vexxy
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/vexxy-xyz/all-vexxy.git
  ref:
    branch: main
  secretRef:
    name: vexxy-git-auth
