- name: Deploy Longhorn Distributed Storage
  hosts: controlplane[0]
  gather_facts: false
  vars:
    cluster_config: "{{ lookup('file', 'tmp/{{ cluster_name }}/cluster_config.json') | from_json }}"
    longhorn_version: "{{ lookup('env', 'LONGHORN_VERSION') }}"
    kubeconfig_file: "{{ lookup('env', 'HOME') }}/.kube/{{ cluster_config.kubeconfig_file_name }}"
  environment:
    KUBECONFIG: "{{ kubeconfig_file }}"
  tasks:
    - name: Disable multipath daemon on all nodes to prevent Longhorn conflicts
      ansible.builtin.shell: |
        systemctl stop multipathd.socket multipathd.service || true
        systemctl disable multipathd.socket multipathd.service || true
        systemctl mask multipathd.service || true
        touch /etc/longhorn-multipath-disabled
      delegate_to: "{{ item }}"
      loop: "{{ groups['all'] }}"
      become: true

    - name: Disable Longhorn scheduling on GPU nodes
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Node
          metadata:
            name: "{{ item }}"
            labels:
              node.longhorn.io/create-default-disk: "false"
      loop: "{{ groups['gpu'] | default([]) }}"
      delegate_to: localhost
      when: groups['gpu'] is defined and groups['gpu'] | length > 0

    - name: Add Longhorn Helm repository
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: https://charts.longhorn.io
      delegate_to: localhost

    - name: Create longhorn-system namespace
      kubernetes.core.k8s:
        name: longhorn-system
        api_version: v1
        kind: Namespace
        state: present
      delegate_to: localhost

    - name: Install Longhorn using Helm
      kubernetes.core.helm:
        name: longhorn
        chart_ref: longhorn/longhorn
        release_namespace: longhorn-system
        create_namespace: true
        values:
          image:
            longhorn:
              engine:
                tag: "v{{ longhorn_version }}"
              manager:
                tag: "v{{ longhorn_version }}"
              ui:
                tag: "v{{ longhorn_version }}"
              instanceManager:
                tag: "v{{ longhorn_version }}"
              shareManager:
                tag: "v{{ longhorn_version }}"
              backingImageManager:
                tag: "v{{ longhorn_version }}"
              supportBundleKit:
                tag: "v{{ longhorn_version }}"
          persistence:
            defaultClass: true
            defaultClassReplicaCount: 3
            defaultDataLocality: best-effort
          defaultSettings:
            defaultDataPath: "/var/lib/longhorn/"
            replicaSoftAntiAffinity: true
            createDefaultDiskLabeledNodes: true
            defaultLonghornStaticStorageClass: longhorn
            backupstorePollInterval: 300
            failedBackupTTL: 1440
            restoreVolumeRecurringJobs: true
            concurrentAutomaticEngineUpgradePerNodeLimit: 3
            systemManagedComponentsNodeSelector: "kubernetes.io/os:linux"
            # Conservative settings for gamma 5-disk storage  
            storageOverProvisioningPercentage: 110   # Conservative over-provisioning (10% buffer)
            storageMinimalAvailablePercentage: 15    # Keep 15% free space minimum
            upgradeChecker: false                    # Disable upgrade checker for stability
            defaultReplicaCount: 3                   # Maintain 3-way replication for safety
            allowRecurringJobWhileVolumeDetached: true
            concurrentReplicaRebuildPerNodeLimit: 5  # Allow more concurrent rebuilds
            concurrentVolumeBackupRestorePerNodeLimit: 5
          longhornManager:
            nodeSelector:
              kubernetes.io/os: "linux"
          longhornDriver:
            nodeSelector:
              kubernetes.io/os: "linux"
          longhornUI:
            nodeSelector:
              kubernetes.io/os: "linux"
      delegate_to: localhost

    - name: Wait for Longhorn to be ready
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: DaemonSet
        name: longhorn-manager
        namespace: longhorn-system
      register: longhorn_daemonset
      until: longhorn_daemonset.resources[0].status.numberReady == longhorn_daemonset.resources[0].status.desiredNumberScheduled
      retries: 60
      delay: 5
      delegate_to: localhost

    - name: Wait for Longhorn StorageClass to be created
      kubernetes.core.k8s_info:
        api_version: storage.k8s.io/v1
        kind: StorageClass
        name: longhorn
      register: longhorn_storageclass
      until: longhorn_storageclass.resources | length > 0
      retries: 30
      delay: 2
      delegate_to: localhost

    - name: Check for existing default storage class
      kubernetes.core.k8s_info:
        api_version: storage.k8s.io/v1
        kind: StorageClass
      register: storage_classes
      delegate_to: localhost

    - name: Remove default annotation from local-path storage class
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: storage.k8s.io/v1
          kind: StorageClass
          metadata:
            name: local-path
            annotations:
              storageclass.kubernetes.io/is-default-class: "false"
      when: storage_classes.resources | selectattr('metadata.name', 'equalto', 'local-path') | list | length > 0
      delegate_to: localhost

    - name: Set Longhorn as default storage class
      kubernetes.core.k8s:
        state: present
        merge_type: merge
        definition:
          apiVersion: storage.k8s.io/v1
          kind: StorageClass
          metadata:
            name: longhorn
            annotations:
              storageclass.kubernetes.io/is-default-class: "true"
      when: longhorn_storageclass.resources | length > 0
      delegate_to: localhost

    - name: Display Longhorn installation status
      debug:
        msg: |
          Longhorn v{{ longhorn_version }} has been successfully installed!
          
          Access Longhorn UI:
          kubectl port-forward -n longhorn-system svc/longhorn-frontend 8080:80
          Then visit: http://localhost:8080
          
          Storage features:
          - Default StorageClass: longhorn (replicas=3)
          - Data locality: best-effort
          - Automatic disk discovery on labeled nodes
          - 1.5TB storage per general node (4.5TB total raw, ~1.5TB usable with 3x replication)
          
          For volume permission issues, use fsGroup in your pods:
          spec:
            securityContext:
              fsGroup: 1000  # Kubernetes handles volume ownership automatically
