---
- name: Setup Longhorn Storage Disks
  hosts: all
  gather_facts: true
  become: true
  vars:
    longhorn_nodes: "{{ lookup('file', 'tmp/{{ cluster_name }}/longhorn_nodes.json') | from_json }}"
    filesystem: "xfs"  # XFS is better for large storage volumes and Longhorn
  tasks:
    - name: Get node metadata for current host
      set_fact:
        current_node: "{{ longhorn_nodes.nodes_with_secondary_disks | selectattr('cluster_name', 'equalto', cluster_name) | selectattr('ipv4.vm_ip', 'equalto', ansible_default_ipv4.address) | first | default({}) }}"

    - name: Skip hosts without secondary disks
      meta: end_host
      when: current_node == {} or not current_node.has_secondary_disks

    - name: Process secondary disks
      include_tasks: tasks/setup-longhorn-disk.yaml
      loop: "{{ current_node.secondary_disks }}"
      loop_control:
        loop_var: disk_item

