---
- name: Reset Node(s)
  hosts: all
  become: true
  vars:
    cluster_config: "{{ lookup('file', 'tmp/{{ cluster_name }}/cluster_config.json') | from_json }}"
    preserve_storage: false
  tasks:
    - name: Run kubeadm reset
      ansible.builtin.command:
        cmd: kubeadm reset -f
      ignore_errors: yes

    - name: Flush iptables rules
      ansible.builtin.iptables:
        flush: yes

    - name: Delete all iptables chains
      ansible.builtin.shell: iptables -X
      ignore_errors: yes

    - name: Clear IPVS tables
      ansible.builtin.shell: ipvsadm --clear
      ignore_errors: yes

    - name: Delete k8s configurations
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/home/{{ cluster_config.ssh.ssh_user }}/.kube/"
        - "/home/{{ cluster_config.ssh.ssh_user }}/kubeadm-config.yaml"
        - "/home/{{ cluster_config.ssh.ssh_user }}/kubeadmcfg.yaml"
        - /etc/kubernetes
        - /etc/default/kubelet
        - /etc/ceph
        - /etc/cni/net.d/05-cilium.conf
        - /etc/cni/net.d/.kubernetes-cni-keep
        - /etc/systemd/system/kubelet.service.d/kubelet.conf
        - /etc/systemd/system/kubelet.service.d/20-etcd-service-manager.conf
        - /var/lib/etcd
        - /var/lib/kubelet
        - /var/backups/etcd
        - /var/lib/rook
        - /var/log/containers
        - /var/log/pods
        - /opt/local-path-provisioner
        - /opt/secrets/kubernetes.io
        - /run/lib/etcd
        - /root/.bootstrap

    - name: Delete all containers
      shell: "ctr -n k8s.io c rm $(ctr -n k8s.io c ls -q) 2>/dev/null || true"
      ignore_errors: true

    - name: Delete all container images
      shell: "ctr -n k8s.io i rm $(ctr -n k8s.io i ls -q) 2>/dev/null || true"
      ignore_errors: true

    # ===== Graceful Longhorn Storage Cleanup =====
    - name: Find Longhorn storage mounts from fstab
      shell: "grep -E '/var/lib/longhorn-disk' /etc/fstab | awk '{print $2}' || true"
      register: longhorn_mounts
      changed_when: false

    - name: Display Longhorn mounts to be unmounted
      debug:
        msg: "Found Longhorn storage mounts: {{ longhorn_mounts.stdout_lines }}"
      when: longhorn_mounts.stdout_lines | length > 0

    - name: Stop Longhorn processes gracefully
      shell: "pkill -f longhorn || true"
      ignore_errors: true
      when: longhorn_mounts.stdout_lines | length > 0

    - name: Wait for Longhorn processes to terminate
      pause:
        seconds: 5
      when: longhorn_mounts.stdout_lines | length > 0

    - name: Unmount Longhorn storage disks gracefully
      mount:
        path: "{{ item }}"
        state: unmounted
      loop: "{{ longhorn_mounts.stdout_lines }}"
      ignore_errors: true
      when: longhorn_mounts.stdout_lines | length > 0

    - name: Remove Longhorn disk entries from fstab
      lineinfile:
        path: /etc/fstab
        regexp: ".*{{ item | regex_escape() }}.*"
        state: absent
        backup: true
      loop: "{{ longhorn_mounts.stdout_lines }}"
      when: longhorn_mounts.stdout_lines | length > 0

    - name: Remove Longhorn mount point directories
      file:
        path: "{{ item }}"
        state: absent
      loop: "{{ longhorn_mounts.stdout_lines }}"
      when: longhorn_mounts.stdout_lines | length > 0

    # ===== General Kubernetes Unmounting =====
    - name: Unmount all Kubernetes mounts
      shell: "for mount in $(mount | grep tmpfs | grep '/var/lib/kubelet' | awk '{ print $3 }') /var/lib/kubelet /var/lib/rancher; do umount $mount 2>/dev/null || true; done"
      ignore_errors: true

    # ===== Disk Wiping (Conditional) =====
    - name: Display storage preservation status
      debug:
        msg: |
          Storage preservation mode: {{ preserve_storage }}
          {% if preserve_storage %}
          WARNING: Storage data will be PRESERVED. Disks will NOT be wiped.
          This means existing Longhorn data will remain on the disks.
          {% else %}
          WARNING: All external storage disks will be WIPED COMPLETELY.
          This will destroy all data on secondary disks.
          {% endif %}

    - name: Find external storage disks to Zap
      # Zap all vd.* disks except for vda, which is the OS disk. All virtio disks start with vd.
      shell: "lsblk -lno NAME | grep -v vda | grep -E '^(vd.*)$' || true"
      register: disk_list
      when: not preserve_storage

    - name: Show external disks that will be zapped
      ansible.builtin.debug:
        msg: "The following disks will be COMPLETELY WIPED: {{ disk_list.stdout_lines }}"
      when: 
        - not preserve_storage
        - disk_list.stdout_lines | length > 0

    - name: Zap external storage disks
      command: "sgdisk --zap-all /dev/{{ item }}"
      loop: "{{ disk_list.stdout_lines }}"
      when: 
        - not preserve_storage
        - disk_list.stdout_lines | length > 0
      ignore_errors: yes

    - name: Reboot nodes
      ansible.builtin.reboot:
        msg: "Rebooting to clean up after kubeadm reset"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
