---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-chopper-screen
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/apps/base/chopper-screen
  prune: true
  wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
