---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-system
  namespace: monitoring
  labels:
    app.kubernetes.io/name: flux-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: flux-system
  namespaceSelector:
    matchNames:
    - flux-system
  endpoints:
  - port: http-metrics
    interval: 30s
    path: /metrics