---
# VirtualService for Hubble UI via Istio Gateway
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: hubble-ui
  namespace: kube-system
spec:
  hosts:
  - "hubble.dunde.live"
  gateways:
  - istio-system/dunde-live-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: hubble-ui.kube-system.svc.cluster.local
        port:
          number: 80
---
# ServiceMonitor for Hubble metrics (Prometheus integration)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hubble-relay-istio
  namespace: kube-system
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      k8s-app: hubble-relay
  endpoints:
  - port: prometheus
    interval: 30s
    path: /metrics