---
# ServiceMonitor for Istio control plane metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-controlplane
  namespace: istio-system
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: istiod
  endpoints:
  - port: http-monitoring
    interval: 30s
    path: /stats/prometheus
---
# ServiceMonitor for Istio data plane (envoy) metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-dataplane
  namespace: istio-system
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchExpressions:
    - key: service.istio.io/canonical-name
      operator: Exists
  endpoints:
  - port: http-envoy-prom
    interval: 30s
    path: /stats/prometheus
---
# ServiceMonitor for Istio ztunnel metrics (available even in ingress-only mode)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-ztunnel-metrics
  namespace: istio-system
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: ztunnel
  endpoints:
  - port: http-monitoring
    interval: 30s
    path: /stats/prometheus
    # Optional: Only scrape if ztunnel service exists
    honorLabels: true