---
name: Renovate

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Dry-Run"
        default: "false"
        required: false
      logLevel:
        description: "Log-Level"
        default: "debug"
        required: false
  schedule:
    # Run every day at 2am UTC
    - cron: "0 2 * * *"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/renovate.yml"
      - "renovate.json"

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42
        id: app-token
        with:
          app-id: "${{ secrets.RENOVATE_APP_ID }}"
          private-key: "${{ secrets.RENOVATE_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Renovate
        uses: renovatebot/github-action@aec779d4f7845f8431ddf403cf9659d4702ddde0
        env:
          # Use GitHub App token for authentication
          RENOVATE_TOKEN: "${{ steps.app-token.outputs.token }}"
          # Repository to renovate
          RENOVATE_REPOSITORIES: "${{ github.repository }}"
          # Set log level based on input or default
          LOG_LEVEL: "${{ github.event.inputs.logLevel || 'info' }}"
          # Dry run mode
          RENOVATE_DRY_RUN: "${{ github.event.inputs.dryRun || 'false' }}"
          # Platform
          RENOVATE_PLATFORM: "github"
          # Require config
          RENOVATE_REQUIRE_CONFIG: "required"
        with:
          configurationFile: renovate.json
          token: "${{ steps.app-token.outputs.token }}"
          mount-docker-socket: true
          renovate-version: "latest"
